version: "3.7"
services:
  asprom:
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    image: asprom
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - crontabs:/var/spool/cron/crontabs
    ports:
      - 8080:8080
  asprom-metrics:
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    image: asprom
    command:
      - python3
      - aspromMetrics.py
    depends_on:
      - mysql
    ports:
      - 5000:5000
  mysql:
    restart: always
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_USER: 'asprom'
      MYSQL_PASSWORD: 'asprom'
      MYSQL_DATABASE: 'asprom'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - "mysqldata:/var/lib/mysql"
      - "./db/ddl.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./docker/my_mem.cnf:/etc/mysql/conf.d/my_mem.cnf"
volumes:
  mysqldata:
  crontabs:

