#! /bin/sh
### BEGIN INIT INFO
# Provides:          asprom
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: asprom assault profile monitor
# Description:       starts the asprom GUI.
### END INIT INFO

# Author: stefan knott <knott@turmair.de>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin

# change this
MAINPATH=/home/asprom/asprom
USER=asprom

DESC="asprom assault profile monitor"
NAME=aspromGUI.py
DAEMON=/usr/bin/python
DAEMON_ARGS="$MAINPATH/$NAME"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
